// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkkvbdmxjmygtdojtlfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtra3ZiZG14am15Z3Rkb2p0bGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTg2NzYsImV4cCI6MjA2NjYzNDY3Nn0.drFCkhBA-AFV9nkGmQPo_d5BRWnVCQWT627OXRrEb2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);